### ISSUE TITLE
Can't open a model after a train where there is a tf.keras.layers.ReLU() layer

### ISSUE THREAD

**Issue by ValentinVignal** [ValentinVignal/midiGenerator#1]
When a model is created and saved with the layer tf.keras.layers.ReLU(). When you try to load it the following error is plotted :

```console
(VirtualEnv) D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\midiGenerator>python generate.py defaultName-denseNet,pc,8-1-0 --pc
Got new full_name : default_name-m()-e(0)-(0)
Get full_name : defaultName-m(denseNet,pc,8)-e(1)-(0)
Traceback (most recent call last):
  File "generate.py", line 45, in <module>
    main()
  File "generate.py", line 37, in main
    my_model = MyModel(load_model=args.load)     # Load the model
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\midiGenerator\src\NN\MyModel.py", line 56, in __init__
    self.load_model(load_model)
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\midiGenerator\src\NN\MyModel.py", line 174, in load_model
    self.my_nn.load(str(path_to_load / 'MyNN'))
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\midiGenerator\src\NN\nn.py", line 124, in load
    self.model = tf.keras.models.load_model(str(path / 'm.h5'), custom_objects={'loss_function': self.loss})
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 230, in loa
d_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 310, in mod
el_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64,
in deserialize
    printable_module_name='layer')
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173,
in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1292, in f
rom_config
    process_layer(layer_data)
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1278, in p
rocess_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64,
in deserialize
    printable_module_name='layer')
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 175,
in deserialize_keras_object
    return cls.from_config(config['config'])
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1606, i
n from_config
    return cls(**config)
  File "D:\Valentin\Etudes\NUS\Dissertation\Projects\midiGenerator\VirtualEnv\lib\site-packages\tensorflow\python\keras\layers\advanced_activations.py", li
ne 318, in __init__
    if negative_slope < 0.:
TypeError: '<' not supported between instances of 'dict' and 'float'
```

**Comment by ValentinVignal** [comment]
This is a problem with the library Tensorflow
It has been resolved in the [comment](https://github.com/tensorflow/tensorflow/issues/22697#issuecomment-436301471) of the [issue](https://github.com/tensorflow/tensorflow/issues/23413#issue-376165509).
**Temporary fix :**
After the `super()` call in the ReLu `init()` function in *tensorflow/python/keras/layers/advanced_activations.py* (around line 310), add the following lines of code:
```python
   if type(max_value) is dict:
        max_value = max_value['value']
   if type(negative_slope) is dict:
        negative_slope = negative_slope['value']
    if type(threshold) is dict:
        threshold = threshold['value']
```
